### ISSUE TITLE
Rename the `otf` branch to `otf-master`

### ISSUE THREAD

**Issue by regner** [OpenTelecom/kazoo#9]
I would like to propose the renaming of the branch `otf` to `otf-master`. We currently have `otf-4.1` and `otf-4.2` which are forks of the 4.1 and 4.2 branches respectively, but then the OTF fork of master is just `otf`.

This is a small difference but it actually causes some added complexity in the scripts I am writing to help keep the OTF branches up to date. Instead of being able to go `otf-$branchNameVariable` I have to add extra code to handle this edge case.

I know it seems minor but it also just helps clarify thing for newer people coming along.

That and my OCD is freaking out.

**Comment by noahmehl** [comment]
Yes, I think that makes more sense.

**Comment by regner** [comment]
This has been done.
